### ISSUE TITLE
Create Node Class

### ISSUE THREAD

**Issue by ghost** [NoticeMeDan/p2p#1]
A "Node" process takes as arguments a local port and optionally the IP/port of another Node process. The Node listens for PUT and GET requests on its local port. NB! "PUT" and "GET" are here just informal message types; they are not necessarily HTTP request verbs.

**Comment by EliasJorgensen** [comment]
Skal splittes op i de forskellige processor - ellers bliver opgaven 70% af hele afleveringen.
